-- Template for file: fellowships_call.html
template1 :: Html ()
template1 = do
  div_ [ class_ "formify" ] $ do
    h2_ [ data_ "fy-title" "fellowship_title" ] $ "Titre de la bourse"
    form_ [ id_ "fy-form-fellowishp_title", enctype_ "multipart/form-data", method_ "post", action_ "/submit/fellowship_title", acceptCharset_ "UTF-8" ] $ do
      fieldset_ $ do
        legend_ [ data_ "fy-abbr" "pi" ] $ "Personnal Information"
        label_ $ do
          "Civility"
          label_ $ do
            input_ [ name_ "fy-pi-civility", type_ "radio", value_ "Mr", required_ "" ]
            "Mr"
          label_ $ do
            input_ [ name_ "fy-pi-civility", type_ "radio", value_ "Ms", required_ "" ]
            "Ms"
        label_ $ do
          "First name"
          input_ [ name_ "fy-pi-firstname", type_ "text", size_ "60", maxlength_ "128", required_ "" ]
        label_ $ do
          "Last name"
          input_ [ name_ "fy-pi-lasttname", type_ "text", size_ "60", maxlength_ "128", required_ "" ]
        label_ $ do
          "Email address"
          span_ [ class_ "fy-info" ] $ "Email address valid during 2020"
          input_ [ name_ "fy-pi-email", type_ "email", size_ "60", maxlength_ "128", required_ "" ]
        label_ $ do
          "Birth Date"
          input_ [ name_ "fy-pi-birthdate", type_ "date", required_ "" ]
        label_ $ do
          "Country of citizenship"
          select_ [ required_ "required", name_ "fy-pi-nationality", required_ "" ] $ do
            option_ [ value_ "", selected_ "selected" ] $ "Select country"
            option_ [ value_ "AF" ] $ "Afghanistan"
            option_ [ value_ "ZA" ] $ "Afrique du Sud"
            option_ [ value_ "AL" ] $ "Albanie"
            option_ [ value_ "DZ" ] $ "Alg\233rie"
            option_ [ value_ "DE" ] $ "Allemagne"
            option_ [ value_ "AD" ] $ "Andorre"
            option_ [ value_ "AO" ] $ "Angola"
            option_ [ value_ "AI" ] $ "Anguilla"
            option_ [ value_ "AQ" ] $ "Antarctique"
            option_ [ value_ "AG" ] $ "Antigua-et-Barbuda"
            option_ [ value_ "AN" ] $ "Antilles n\233erlandaises"
            option_ [ value_ "SA" ] $ "Arabie Saoudite"
            option_ [ value_ "AR" ] $ "Argentine"
            option_ [ value_ "AM" ] $ "Arm\233nie"
            option_ [ value_ "AW" ] $ "Aruba"
            option_ [ value_ "AU" ] $ "Australie"
            option_ [ value_ "AT" ] $ "Autriche"
            option_ [ value_ "AZ" ] $ "Azerba\239djan"
            option_ [ value_ "BS" ] $ "Bahamas"
            option_ [ value_ "BH" ] $ "Bahre\239n"
            option_ [ value_ "BD" ] $ "Bangladesh"
            option_ [ value_ "BB" ] $ "Barbade"
            option_ [ value_ "BE" ] $ "Belgique"
            option_ [ value_ "BZ" ] $ "Belize"
            option_ [ value_ "BM" ] $ "Bermudes"
            option_ [ value_ "BT" ] $ "Bhoutan"
            option_ [ value_ "MM" ] $ "Birmanie"
            option_ [ value_ "BY" ] $ "Bi\233lorussie"
            option_ [ value_ "BO" ] $ "Bolivie"
            option_ [ value_ "BA" ] $ "Bosnie-Herz\233govine"
            option_ [ value_ "BW" ] $ "Botswana"
            option_ [ value_ "BN" ] $ "Brunei"
            option_ [ value_ "BR" ] $ "Br\233sil"
            option_ [ value_ "BG" ] $ "Bulgarie"
            option_ [ value_ "BF" ] $ "Burkina Faso"
            option_ [ value_ "BI" ] $ "Burundi"
            option_ [ value_ "BJ" ] $ "B\233nin"
            option_ [ value_ "KH" ] $ "Cambodge"
            option_ [ value_ "CM" ] $ "Cameroun"
            option_ [ value_ "CA" ] $ "Canada"
            option_ [ value_ "CV" ] $ "Cap-Vert"
            option_ [ value_ "CL" ] $ "Chili"
            option_ [ value_ "CN" ] $ "Chine"
            option_ [ value_ "CY" ] $ "Chypre"
            option_ [ value_ "CO" ] $ "Colombie"
            option_ [ value_ "KM" ] $ "Comores"
            option_ [ value_ "CG" ] $ "Congo (Brazzaville)"
            option_ [ value_ "CD" ] $ "Congo (Kinshasa)"
            option_ [ value_ "KP" ] $ "Cor\233e du Nord"
            option_ [ value_ "KR" ] $ "Cor\233e du Sud"
            option_ [ value_ "CR" ] $ "Costa Rica"
            option_ [ value_ "HR" ] $ "Croatie"
            option_ [ value_ "CU" ] $ "Cuba"
            option_ [ value_ "CW" ] $ "Cura\231ao"
            option_ [ value_ "CI" ] $ "C\244te d\8217Ivoire"
            option_ [ value_ "DK" ] $ "Danemark"
            option_ [ value_ "DJ" ] $ "Djibouti"
            option_ [ value_ "DM" ] $ "Dominique"
            option_ [ value_ "ES" ] $ "Espagne"
            option_ [ value_ "EE" ] $ "Estonie"
            option_ [ value_ "FJ" ] $ "Fidji"
            option_ [ value_ "FI" ] $ "Finlande"
            option_ [ value_ "FR" ] $ "France"
            option_ [ value_ "GA" ] $ "Gabon"
            option_ [ value_ "GM" ] $ "Gambie"
            option_ [ value_ "GH" ] $ "Ghana"
            option_ [ value_ "GI" ] $ "Gibraltar"
            option_ [ value_ "GD" ] $ "Grenade"
            option_ [ value_ "GL" ] $ "Groenland"
            option_ [ value_ "GR" ] $ "Gr\232ce"
            option_ [ value_ "GP" ] $ "Guadeloupe"
            option_ [ value_ "GU" ] $ "Guam"
            option_ [ value_ "GT" ] $ "Guatemala"
            option_ [ value_ "GG" ] $ "Guernesey"
            option_ [ value_ "GN" ] $ "Guin\233e"
            option_ [ value_ "GW" ] $ "Guin\233e-Bissau"
            option_ [ value_ "GQ" ] $ "Guin\233e \233quatoriale"
            option_ [ value_ "GY" ] $ "Guyana"
            option_ [ value_ "GF" ] $ "Guyane fran\231aise"
            option_ [ value_ "GE" ] $ "G\233orgie"
            option_ [ value_ "GS" ] $ "G\233orgie du Sud et les \206les Sandwich du Sud"
            option_ [ value_ "HT" ] $ "Ha\239ti"
            option_ [ value_ "HN" ] $ "Honduras"
            option_ [ value_ "HK" ] $ "Hong Kong R.A.S., Chine"
            option_ [ value_ "HU" ] $ "Hongrie"
            option_ [ value_ "IN" ] $ "Inde"
            option_ [ value_ "ID" ] $ "Indon\233sie"
            option_ [ value_ "IQ" ] $ "Irak"
            option_ [ value_ "IR" ] $ "Iran"
            option_ [ value_ "IE" ] $ "Irlande"
            option_ [ value_ "IS" ] $ "Islande"
            option_ [ value_ "IL" ] $ "Isra\235l"
            option_ [ value_ "IT" ] $ "Italie"
            option_ [ value_ "JM" ] $ "Jama\239que"
            option_ [ value_ "JP" ] $ "Japon"
            option_ [ value_ "JE" ] $ "Jersey"
            option_ [ value_ "JO" ] $ "Jordanie"
            option_ [ value_ "KZ" ] $ "Kazakhstan"
            option_ [ value_ "KE" ] $ "Kenya"
            option_ [ value_ "KG" ] $ "Kirghizistan"
            option_ [ value_ "KI" ] $ "Kiribati"
            option_ [ value_ "KW" ] $ "Kowe\239t"
            option_ [ value_ "LA" ] $ "Laos"
            option_ [ value_ "LS" ] $ "Lesotho"
            option_ [ value_ "LV" ] $ "Lettonie"
            option_ [ value_ "LB" ] $ "Liban"
            option_ [ value_ "LR" ] $ "Lib\233ria"
            option_ [ value_ "LI" ] $ "Liechtenstein"
            option_ [ value_ "LT" ] $ "Lituanie"
            option_ [ value_ "LU" ] $ "Luxembourg"
            option_ [ value_ "LY" ] $ "Lybie"
            option_ [ value_ "MO" ] $ "Macao R.A.S., Chine"
            option_ [ value_ "MK" ] $ "Mac\233doine"
            option_ [ value_ "MG" ] $ "Madagascar"
            option_ [ value_ "MY" ] $ "Malaisie"
            option_ [ value_ "MW" ] $ "Malawi"
            option_ [ value_ "MV" ] $ "Maldives"
            option_ [ value_ "ML" ] $ "Mali"
            option_ [ value_ "MT" ] $ "Malte"
            option_ [ value_ "MA" ] $ "Maroc"
            option_ [ value_ "MQ" ] $ "Martinique"
            option_ [ value_ "MU" ] $ "Maurice"
            option_ [ value_ "MR" ] $ "Mauritanie"
            option_ [ value_ "YT" ] $ "Mayotte"
            option_ [ value_ "MX" ] $ "Mexique"
            option_ [ value_ "FM" ] $ "Micron\233sie"
            option_ [ value_ "MD" ] $ "Moldavie"
            option_ [ value_ "MC" ] $ "Monaco"
            option_ [ value_ "MN" ] $ "Mongolie"
            option_ [ value_ "MS" ] $ "Montserrat"
            option_ [ value_ "ME" ] $ "Mont\233n\233gro"
            option_ [ value_ "MZ" ] $ "Mozambique"
            option_ [ value_ "NA" ] $ "Namibie"
            option_ [ value_ "NR" ] $ "Nauru"
            option_ [ value_ "NI" ] $ "Nicaragua"
            option_ [ value_ "NE" ] $ "Niger"
            option_ [ value_ "NG" ] $ "Nigeria"
            option_ [ value_ "NU" ] $ "Niue"
            option_ [ value_ "NO" ] $ "Norv\232ge"
            option_ [ value_ "NC" ] $ "Nouvelle-Cal\233donie"
            option_ [ value_ "NZ" ] $ "Nouvelle-Z\233lande"
            option_ [ value_ "NP" ] $ "N\233pal"
            option_ [ value_ "OM" ] $ "Oman"
            option_ [ value_ "UG" ] $ "Ouganda"
            option_ [ value_ "UZ" ] $ "Ouzb\233kistan"
            option_ [ value_ "PK" ] $ "Pakistan"
            option_ [ value_ "PW" ] $ "Palaos"
            option_ [ value_ "PA" ] $ "Panama"
            option_ [ value_ "PG" ] $ "Papouasie-Nouvelle-Guin\233e"
            option_ [ value_ "PY" ] $ "Paraguay"
            option_ [ value_ "NL" ] $ "Pays-Bas"
            option_ [ value_ "BQ" ] $ "Pays-Bas carib\233ens"
            option_ [ value_ "PH" ] $ "Philippines"
            option_ [ value_ "PN" ] $ "Pitcairn"
            option_ [ value_ "PL" ] $ "Pologne"
            option_ [ value_ "PF" ] $ "Polyn\233sie fran\231aise"
            option_ [ value_ "PR" ] $ "Porto Rico"
            option_ [ value_ "PT" ] $ "Portugal"
            option_ [ value_ "PE" ] $ "P\233rou"
            option_ [ value_ "QA" ] $ "Qatar"
            option_ [ value_ "RO" ] $ "Roumanie"
            option_ [ value_ "GB" ] $ "Royaume-Uni"
            option_ [ value_ "RU" ] $ "Russie"
            option_ [ value_ "RW" ] $ "Rwanda"
            option_ [ value_ "CF" ] $ "R\233publique centrafricaine"
            option_ [ value_ "DO" ] $ "R\233publique dominicaine"
            option_ [ value_ "CZ" ] $ "R\233publique tch\232que"
            option_ [ value_ "RE" ] $ "R\233union"
            option_ [ value_ "EH" ] $ "Sahara occidental"
            option_ [ value_ "BL" ] $ "Saint-Barth\233lemy"
            option_ [ value_ "KN" ] $ "Saint-Christophe-et-Ni\233v\232s"
            option_ [ value_ "SM" ] $ "Saint-Marin"
            option_ [ value_ "SX" ] $ "Saint-Martin"
            option_ [ value_ "MF" ] $ "Saint-Martin (partie fran\231aise)"
            option_ [ value_ "PM" ] $ "Saint-Pierre-et-Miquelon"
            option_ [ value_ "VC" ] $ "Saint-Vincent-et-les-Grenadines"
            option_ [ value_ "SH" ] $ "Sainte-H\233l\232ne"
            option_ [ value_ "LC" ] $ "Sainte-Lucie"
            option_ [ value_ "SV" ] $ "Salvador"
            option_ [ value_ "WS" ] $ "Samoa"
            option_ [ value_ "AS" ] $ "Samoa am\233ricaines"
            option_ [ value_ "ST" ] $ "Sao Tom\233-et-Principe"
            option_ [ value_ "RS" ] $ "Serbie"
            option_ [ value_ "SC" ] $ "Seychelles"
            option_ [ value_ "SL" ] $ "Sierra Leone"
            option_ [ value_ "SG" ] $ "Singapour"
            option_ [ value_ "SK" ] $ "Slovaquie"
            option_ [ value_ "SI" ] $ "Slov\233nie"
            option_ [ value_ "SO" ] $ "Somalie"
            option_ [ value_ "SD" ] $ "Soudan"
            option_ [ value_ "SS" ] $ "Soudan du Sud"
            option_ [ value_ "LK" ] $ "Sri Lanka"
            option_ [ value_ "CH" ] $ "Suisse"
            option_ [ value_ "SR" ] $ "Suriname"
            option_ [ value_ "SE" ] $ "Su\232de"
            option_ [ value_ "SJ" ] $ "Svalbard et \206le Jan Mayen"
            option_ [ value_ "SZ" ] $ "Swaziland"
            option_ [ value_ "SY" ] $ "Syrie"
            option_ [ value_ "SN" ] $ "S\233n\233gal"
            option_ [ value_ "TJ" ] $ "Tadjikistan"
            option_ [ value_ "TZ" ] $ "Tanzanie"
            option_ [ value_ "TW" ] $ "Ta\239wan"
            option_ [ value_ "TD" ] $ "Tchad"
            option_ [ value_ "TF" ] $ "Terres australes fran\231aises"
            option_ [ value_ "IO" ] $ "Territoire britannique de l'oc\233an Indien"
            option_ [ value_ "PS" ] $ "Territoire palestinien"
            option_ [ value_ "TH" ] $ "Tha\239lande"
            option_ [ value_ "TL" ] $ "Timor oriental"
            option_ [ value_ "TG" ] $ "Togo"
            option_ [ value_ "TK" ] $ "Tokelau"
            option_ [ value_ "TO" ] $ "Tonga"
            option_ [ value_ "TT" ] $ "Trinit\233-et-Tobago"
            option_ [ value_ "TN" ] $ "Tunisie"
            option_ [ value_ "TM" ] $ "Turkm\233nistan"
            option_ [ value_ "TR" ] $ "Turquie"
            option_ [ value_ "TV" ] $ "Tuvalu"
            option_ [ value_ "UA" ] $ "Ukraine"
            option_ [ value_ "UY" ] $ "Uruguay"
            option_ [ value_ "VU" ] $ "Vanuatu"
            option_ [ value_ "VA" ] $ "Vatican"
            option_ [ value_ "VE" ] $ "Venezuela"
            option_ [ value_ "VN" ] $ "Vietnam"
            option_ [ value_ "WF" ] $ "Wallis et Futuna"
            option_ [ value_ "YE" ] $ "Y\233men"
            option_ [ value_ "ZM" ] $ "Zambie"
            option_ [ value_ "ZW" ] $ "Zimbabwe"
            option_ [ value_ "EG" ] $ "\201gypte"
            option_ [ value_ "AE" ] $ "\201mirats arabes unis"
            option_ [ value_ "EC" ] $ "\201quateur"
            option_ [ value_ "ER" ] $ "\201rythr\233e"
            option_ [ value_ "US" ] $ "\201tats-Unis"
            option_ [ value_ "ET" ] $ "\201thiopie"
            option_ [ value_ "BV" ] $ "\206le Bouvet"
            option_ [ value_ "CX" ] $ "\206le Christmas"
            option_ [ value_ "IM" ] $ "\206le de Man"
            option_ [ value_ "NF" ] $ "\206le Norfolk"
            option_ [ value_ "AX" ] $ "\206les Aland"
            option_ [ value_ "KY" ] $ "\206les Ca\239mans"
            option_ [ value_ "CC" ] $ "\206les Cocos (Keeling)"
            option_ [ value_ "CK" ] $ "\206les Cook"
            option_ [ value_ "FO" ] $ "\206les F\233ro\233"
            option_ [ value_ "HM" ] $ "\206les Heard et MacDonald"
            option_ [ value_ "FK" ] $ "\206les Malouines"
            option_ [ value_ "MP" ] $ "\206les Mariannes du Nord"
            option_ [ value_ "MH" ] $ "\206les Marshall"
            option_ [ value_ "UM" ] $ "\206les mineures \233loign\233es des \201tats-Unis"
            option_ [ value_ "SB" ] $ "\206les Salomon"
            option_ [ value_ "TC" ] $ "\206les Turques-et-Ca\239ques"
            option_ [ value_ "VI" ] $ "\206les Vierges am\233ricaines"
            option_ [ value_ "VG" ] $ "\206les Vierges britanniques"
        fieldset_ $ do
          legend_ [ data_ "fy-abbr" "pa" ] $ "Postmail address"
          label_ $ do
            "City/Area"
            input_ [ name_ "fy-pi-pa-city", type_ "text", size_ "60", maxlength_ "128", required_ "" ]
          label_ $ do
            "Country"
            input_ [ name_ "fy-pi-pa-country", type_ "text", size_ "60", maxlength_ "128", required_ "" ]
      fieldset_ $ do
        legend_ [ data_ "fy-abbr" "ab" ] $ "Academic background"
        label_ $ do
          "PhD defence Date"
          input_ [ name_ "fy-ab-phd", type_ "date", required_ "" ]
        label_ $ do
          "University"
          input_ [ name_ "fy-ab-university", type_ "text", size_ "60", maxlength_ "128", required_ "" ]
        label_ $ do
          "Research specialty/focus"
          label_ $ do
            input_ [ name_ "fy-ab-specialty", type_ "radio", value_ "spe1", required_ "" ]
            "Mathematics for Life Scienses"
          label_ $ do
            input_ [ name_ "fy-ab-specialty", type_ "radio", value_ "spe2", required_ "" ]
            "Mathematics in Computational Science and Engineering"
          label_ $ do
            input_ [ name_ "fy-ab-specialty", type_ "radio", value_ "spe3", required_ "" ]
            "Mathematics for AI"
          label_ $ do
            input_ [ name_ "fy-ab-specialty", type_ "radio", value_ "spe4", required_ "" ]
            "Mathematics and Theoretical Physics"
          label_ $ do
            input_ [ name_ "fy-ab-specialty", type_ "radio", value_ "spe5", required_ "" ]
            "Other maths"
      fieldset_ $ do
        legend_ [ data_ "fy-abbr" "files" ] $ "Required files"
        p_ "Please upload the following files in PDF format (extension of the files=pdf).\n      For the copies of the articles, please either compress the pdf version of\n      the articles in a zip archive (extension of the archive=zip) or glue them in a single pdf file.\n        All applications with some file in a non PDF format won't be considered."
        label_ $ do
          span_ [ class_ "fy-info" ] $ "Files must have maximal size of 8 Mo. Only pdf !"
          "Application Letter"
          input_ [ class_ "fy-files", data_ "fy-files-max" "8", name_ "fy-files-application-letter", type_ "file", accept_ ".pdf", required_ "" ]
        label_ $ do
          span_ [ class_ "fy-info" ] $ "Files must have maximal size of 8 Mo. Only pdf !"
          "Curriculum Vitae"
          input_ [ class_ "fy-files", data_ "fy-files-max" "8", name_ "fy-files-cv", type_ "file", accept_ ".pdf", required_ "" ]
        label_ $ do
          span_ [ class_ "fy-info" ] $ "Files must have maximal size of 8 Mo. Only pdf !"
          "Detailed research project"
          input_ [ class_ "fy-files", data_ "fy-files-max" "8", name_ "fy-files-research-project", type_ "file", accept_ ".pdf", required_ "" ]
        label_ $ do
          span_ [ class_ "fy-info" ] $ "Files must have maximal size of 8 Mo. Only pdf !"
          "Publication list"
          input_ [ class_ "fy-files", data_ "fy-files-max" "8", name_ "fy-files-publications-list", type_ "file", accept_ ".pdf", required_ "" ]
        label_ $ do
          span_ [ class_ "fy-info" ] $ "Files must have maximal size of 8 Mo. Only pdf !"
          "You may join up to five of your most significant articles,\n        either in full length or through extracts"
          input_ [ class_ "fy-files", data_ "fy-files-max" "5", name_ "fy-files-articles", type_ "file", accept_ ".pdf,.zip", multiple_ "", required_ "" ]
      fieldset_ $ do
        legend_ [ data_ "fy-abbr" "referees" ] $ "Two scientify referees"
        "Please suggest at least one referee, who would be willing to write a recommandation letter for your application. This letter will be direcly requested by the FMJH. Be aware that the letter of referees and the scientific contact have to arrive before the deadline of the call of application (31 January 2020, 12:00pm)."
        label_ $ do
          "Referee 1: First name and Last name"
          input_ [ type_ "text", name_ "fy-referees-ref1-name", required_ "", size_ "60", maxlength_ "128" ]
        label_ $ do
          "Referee 1: Email"
          input_ [ type_ "email", name_ "fy-referees-ref1-email", required_ "", size_ "60", maxlength_ "128" ]
        label_ $ do
          "Referee 2: First name and Last name"
          input_ [ type_ "text", name_ "fy-referees-ref2-name", size_ "60", maxlength_ "128" ]
        label_ $ do
          "Referee 1: Email"
          input_ [ type_ "email", name_ "fy-referees-ref2-email", size_ "60", maxlength_ "128" ]
      input_ [ type_ "submit", value_ "submit" ]

